// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ai-analyze-pdf'
  | 'ai-item-type-not-supported'
  | 'ai-processing'
  | 'ai-processing-complete'
  | 'ai-processing-error'
  | 'ai-processing-failed'
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'pref-api-url'
  | 'pref-enable-both'
  | 'pref-enable-keywords'
  | 'pref-enable-summary'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
